language: node_js
node_js:
  - 'stable'
  - '6'
services:
  - docker
script:
  - yarn run build --release
  - docker build -t toccoag/dashboard .
deploy:
  provider: script
  script: .docker/docker_push
  on:
    branch: master
    node_js: stable
